chose_from = "اختار من القائمة 🎛"

#جداول المحضرات
term1_Table_of_lectures = "📇 جدول محاضرات الكورس الاول 📇"
term2_Table_of_lectures = "📇 جدول محاضرات الكورس الثاني 📇"

#نصوص يعاد استخدامها
back_term1 = "ارجع الى المواد ⬅️"
back_term2 = "ارجع الى المواد ◀️"

#ايموجيات 
nw1_emj = "🔌"
nw2_emj = "📡"
ai_emj = "🤖"
cm1_emj = "🧮"
cm2_emj = "📟"
mm_emj = "🖼️"
se_emj = "📐"
en_emj = "🇬🇧"
or_emj = "🔎"
dm_emj = "⚒"
de_emj = "🔐"
ddb_emj = "🛢"
wp_emj = "🌐"

# متغيرات الكورس الاول
networks1_lab_title = f"شبكات حاسوب1 عملي {nw1_emj}"
networks1_theo_title = f"شبكات حاسوب1 نضري {nw1_emj}"
ai_lab_title = f"ذكاء أصطناعي عملي {ai_emj}"
ai_theo_title = f"ذكاء أصطناعي نضري {ai_emj}"
multimedia_lab_title = f"وسائط متعددة عملي {mm_emj}"
multimedia_theo_title = f"وسائط متعددة نضري {mm_emj}"
software_engineering_lab_title = f"هندسة برمجات عملي {se_emj}"
software_engineering_theo_title = f"هندسة برمجات نضري {se_emj}"
compilers1_lab_title = f"مترجمات1 عملي {cm1_emj}"
compilers1_theo_title = f"مترجمات1 نضري {cm1_emj}"
english_title = f"اللغة الانكليزية {en_emj}"
operations_research_title = f"بحوث عمليات {or_emj}"

#متغيرات الكورس الثاني
web_prog_title = f"برمجة مواقع {wp_emj}"
networks2_lab_title = f"شبكات حاسوب2 عملي {nw2_emj}"
networks2_theo_title = f"شبكات حاسوب2 نضري {nw2_emj}"
data_mining_lab_title = f"تنقيب بيانات عملي {dm_emj}"
data_mining_theo_title = f"تنقيب بيانات نضري {dm_emj}"
dis_db_lab_title = f"قواعد البيانات الموزعة عملي {ddb_emj}"
dis_db_theo_title = f"قواعد البيانات الموزعة نضري {ddb_emj}"
data_enc_lab_title = f"تشفير بيانات عملي {de_emj}"
data_enc_theo_title = f"تشفير بيانات نضري {de_emj}"
compilers2_lab_title = f"مترجمات2 عملي {cm2_emj}"
compilers2_theo_title = f"مترجمات2 نضري {cm2_emj}"

about_bot_msg = ("<b>● عن بوت @cs_stg3_bot:</b>\n\n"
        "<b>• بوت ملازم وملخصات وأشياء مساعدة لطلاب المرحلة الثالثة قسم علوم الحاسوب في كلية علوم الحاسوب وتكنولوجيا المعلومات جامعة واسط دفعة 2022-2025.</b>\n\n"
        "<b>• البوت يسهل وصول الطالب للمادة وكل شيء يخصها من ملازم أصلية ومترجمة أو ملخصات أو البرامج التي يُطبق عليها الجانب العملي.</b>\n\n"
        "<b>• مصادر البوت هي من القنوات الرئيسية للمرحلة الثالثة دفعة 2022-2025:</b>\n\n"
        "  ⏎ قناة الكورس الثاني: \nرابط القناة: @cs_stg3\n\n"
        "  ⏎ قناة الكورس الأول + ملازم السنة السابقة: \nرابط القناة: @cs_stg3_deleted\n\n"
        "  ⏎ قناة المخلصات + الملازم المترجمة + الأسئلة والحلول: \nرابط القناة: @cs_stg3_onefile\n\n"
        "  ⏎ قناة البرامج: \nرابط القناة: @cs_apps\n\n"
        "<b>• تم إنشاء البوت بتاريخ 2024/7/28 بلغة Python مع مكتبة telebot من برمجة @ab0_alhasan.</b>\n\n"
        "<b>• إذا أعجبك البوت، يمكنك تقييمه من خلال /rating.</b>\n\n\n"
        "<blockquote> <b>• ملاحظات ⚠:</b>\n\n"
        "  • يُستخدم البوت أساسًا عبر الأزرار الموجودة في قائمة التحكم التي تحمل رمز 🎛، بالإضافة إلى الأوامر مثل /start لتحديث البوت و /term1 لعرض قائمة الكورس الأول و /term2 لعرض قائمة الكورس الثاني. يُطلب من المستخدمين عدم إرسال أي رسائل نصية مباشرة إلى البوت.\n\n"
        "  • جميع الرسائل المتبادلة بين المستخدم والبوت تظل سرية تمامًا ولن يتم تحويلها أو مشاركتها مع أي طرف آخر. الاستثناء الوحيد هو عند استخدام أزرار قائمة تقييم البوت، حيث سيتم إرسال تقييمات المستخدم إلى المسؤول عن البوت، @ab0_alhasan، و بأمكانه معرفة المعرف واسم الطالب.\n\n"
        "  • رغم ذلك، يُنصح بعدم كتابة رسائل خاصة وذات أهمية داخل البوت، حيث لا يمكن ضمان حماية 100% للخصوصية في جميع الحالات.</blockquote>\n\n"
        "<b>• السورس كود للبوت مع الملفات:</b> <a href='https://github.com/AboALhasanx/cs.stg3.bot'>https://github.com/AboALhasanx/cs.stg3.bot</a>\n\n"
        "<b>✍🏻 ابـوالــحسـن: @ab0_alhasan</b>")
